#!/bin/bash


tmux new-session -d -scyber -nscanning

tmux neww -nmain
tmux split-window -v

tmux neww -dnsecondary

tmux neww -dnwriteup

tmux neww -dnhelp

tmux neww -dnvpn

tmux neww -dnmisc

tmux select-window -t 0

tmux attach -dtcyber
