#!/bin/bash

XDIR=$HOME/.config/xorg
DIFFB=$(diff $XDIR/.xinitrc $XDIR/.xinitrc_bspwm)
DIFFG=$(diff $XDIR/.xinitrc $XDIR/.xinitrc_gnome)

# choose WM/DE
echo -en "\nSelect display option:\n \n1) BSPWM\n \n2) GNOME\n \nSelection: "
read -r
choice=$REPLY

case "$choice" in
	'1')
		if [ "$DIFFB" != "" ]; then
			cp $XDIR/.xinitrc $XDIR/.xinitrc.bak && cp $XDIR/.xinitrc_bspwm $XDIR/.xinitrc
		fi
		echo "can now launch bspwm with startx"
		#startx
	;;
	'2')
		if [ "$DIFFG" != "" ]; then
			cp $XDIR/.xinitrc $XDIR/.xinitrc.bak && cp $XDIR/.xinitrc_gnome $XDIR/.xinitrc
		fi
		echo "can now launch gnome with startx"
		#startx
	;;
	'*')
		echo "Invalid option. Indicate choice with number for display option."
	;;
esac
